---
title: "periSCOPE™: Massachusetts Cannabis Industry"
author: "by operations | architects, llc"
output:
  flexdashboard::flex_dashboard:
    theme:
      bg: '#FFFFFF'
      fg: '#000000'
 #     primary: '#8F0000'
      primary: '#020251'
      base_font:
        google: Roboto Condensed
      code_font:
        google: JetBrains Mono
    orientation: rows
    vertical_layout: scroll
runtime: shiny

---

```{r setup, global, include=FALSE}

library(shiny)
library(tidyverse)
library(plotly)
library(lubridate)
library(kableExtra)
library(DT)
library(shinyWidgets)
#library(leaflet)
library(maps)
library(formattable)
library(zoo)
library(svglite)
library(gt)
library(glue)
library(fable)
library(fabletools)
#library(tsibble)
#library(tsibbledata)
# library(feasts)
# library(scales)
# library(forecast)
# library(TTR)
# library(EnvStats)
# library(truncnorm)
library(reshape)
library(thematic)
# library(seasonal)
library(vistime)
library(flexdashboard)
library(foreign)
library(geosphere)
# library(remotes)
# remotes::install_github('rstudio/flexdashboard')
# library(flexdashboard)

# Install thematic and un-comment for themed static plots (i.e., ggplot2)
thematic::thematic_rmd()


# yields <- read.csv("yield.csv")
# 
# tiers <- read.csv('Tier_data.csv')
# tiers <- dplyr::rename(tiers, tier=Tier)
# 
# productGroups <- reactive ({
#   read_csv("Product_Group.csv", 
#     col_types = cols(...1 = col_skip(), X = col_skip()))
# })
# 
# Conversion_Factors <- read.csv('Conversion_Factors.csv')
# Recipes <- read.csv('Recipes.csv')
# 
# oa_footnote <- "Source: operations | architects"
# 
# 
# productGroupsNames <- reactive ({
#   n<-colnames(productGroups())
#   grep("Units",grep("Group",n,value=TRUE), invert=TRUE, value=TRUE)
# })

############  PATHS AND WORKING DIRECTORIES ####################

ccc_LastPeriod <- "20230808"
ccc_ThisPeriod <- "20230906"
leadTimeFile <- "20230808"
forecastFile <- "20230215"


path_to_ThisPeriod<- paste('Data/',ccc_ThisPeriod,sep='')
path_to_output_directory <- paste('Data/',ccc_ThisPeriod, '/ccc',ccc_ThisPeriod,'output',sep="")
path_to_LastPeriod <- paste('Data/',ccc_LastPeriod,sep='')
path_to_leadTimeFile <- paste('Data/',leadTimeFile,sep='')
path_to_forecastFile <- paste('Data/',forecastFile, '/ccc',forecastFile,'output',sep="")

# 
# ##########################################
# # Load city demographic data
# 
# city_df <- read.dbf("CENSUS2020TOWNS_POLY.dbf", as.is = TRUE)
# 
# city_df$INTPTLAT20 <- as.numeric(city_df$INTPTLAT20)
# city_df$INTPTLON20 <- as.numeric(city_df$INTPTLON20)
# 
# 
# ##########  LOAD AND MASSAGE DATA ##############
# 
# MSFS_df <- read.csv(paste(path_to_ThisPeriod,'/Sales_and_Distribution/AU_Marijuana_Establishment_Facility_Statistics.csv',sep=''), header=TRUE, sep=",")
# 
# 
# MSFSLastPeriod_df <- read.csv(paste(path_to_LastPeriod,'/Sales_and_Distribution/AU_Marijuana_Establishment_Facility_Statistics.csv',sep=''), header=TRUE, sep=",")
# 
# 
# 
# MELA_Pending_df<- read.csv(paste(path_to_ThisPeriod,'/Applications_and_Licensure/AU_Marijuana_Establishment_License_and_Applications-Approved_Pending_Re-Opened.csv',sep=''), header=TRUE, sep=",")
# 
# 
# 
# 
# MELA_Pending_LastPeriod_df<- read.csv(paste(path_to_LastPeriod,'/Applications_and_Licensure/AU_Marijuana_Establishment_License_and_Applications-Approved_Pending_Re-Opened.csv',sep=''), header=TRUE, sep=",")
# 
# MELA_Approved_df<- read.csv(paste(path_to_ThisPeriod,'/Applications_and_Licensure/AU_Marijuana_Establishment_License_and_Applications-Approved.csv',sep=''), header=TRUE, sep=",")
# 
# 
# MELA_Approved_LastPeriod_df<- read.csv(paste(path_to_LastPeriod,'/Applications_and_Licensure/AU_Marijuana_Establishment_License_and_Applications-Approved.csv',sep=''),header=TRUE, sep=",")
# 
# 
# 
# 
# ### Benchmark Price
# 
# MPPO_df<- read.csv(paste(path_to_ThisPeriod,'/Sales_and_Distribution/AU_Average_Monthly_Price_per_Ounce_for_Adult-Use_Cannabis.csv',sep=''), header=TRUE, sep=",")
# 
# 
# ### Lead Time File
# 
# lT_df<- read_csv(paste(path_to_leadTimeFile,"/Applications_and_Licensure/AU_Marijuana_Establishment_License_and_Applications-Approved_Pending_Re-Opened.csv",sep=""))
# 
# 
#  
# ###############################
# 
# ### Plant Activity File
# 
# plantActivity_df <- read_csv(paste(path_to_ThisPeriod, "/Sales_and_Distribution/AU_Marijuana_Establishment_Adult-use_Plant_Activity_and_Volume.csv", sep=""), col_types = cols(ActivitySummaryDate = col_date(format = "%m/%d/%Y")))
# 
# plantActivity_df <- plantActivity_df %>% 
#   group_by(ActivitySummaryDate) %>%
#   mutate(consPlantHarvestedCount = sum(PlantHarvestedCount)) %>%
#   arrange(ActivitySummaryDate) %>%
#   ungroup()
# 
# plantActivity_df$lag_PlantHarvestedCount <- lag(plantActivity_df$PlantHarvestedCount, 1)
# plantActivity_df$dailyPlantHarvestedCount <- plantActivity_df$consPlantHarvestedCount - plantActivity_df$lag_PlantHarvestedCount
# plantActivity_df$dailyPlantHarvestedCount[is.na(plantActivity_df$dailyPlantHarvestedCount)] <- 0
# 
# ###############################
# 
# products <- sort(unique(paste(MSFS_df$ProductCategoryName,' - ', MSFS_df$UnitOfMeasureName,sep="")))


```


Overview {data-orientation=rows}
=========================================
Inputs {.sidebar data-width=300}
-----------------------------------------
<h3>Welcome!</h3>

periSCOPE™ is operations|architects's proprietary analytics workbench for  analyzing the dynamics of the Massachusetts cannabis industry.  

We incorporate leading machine learning and artificial intelligence algorithms into our analytics, models and forecasts. Using periSCOPE™, investors, license holders, and potential licensees can gain insight into the state of the industry and build confidence to make smart investment and operating decisions. 

Use of this platform is subject to the Disclaimer notice under the 'Other Information' tab on this page.  If you have questions about the data, the analytics, the models or the visualizations, please contact <a href='mailto:chris.olaughlin@operationsarchitects.com'>Chris O'Laughlin</a>.
```{r}
hr()
h5('Date of File Updates')
h6(paste('Date of current period files: ', format(as.Date(ccc_ThisPeriod,"%Y%m%d"),format="%b %d, %Y")))

h6(paste('Date of previous period files: ', format(as.Date(ccc_LastPeriod,"%Y%m%d"),format="%b %d, %Y")))

h6(paste('Date of Files used for Lead Time Analysis: ',format(as.Date(leadTimeFile,"%Y%m%d"),format="%b %d, %Y")))

hr()
h5('Controls')
sliderInput("maSalesTaxRate", label = h6("MA Sales Tax Rate (%)"), min = 0, 
        max = 20, value = 6.25, step=.25)
sliderInput("maExciseTaxRate", label = h6("MA Excise Tax Rate (%)"), min = 0, 
        max = 20, value = 10.75, step=.25)
sliderInput("municipalImpactFeeRate", label = h6("Municipal Impact Fee Rate (%)"), min = 0, 
        max = 20, value = 3, step=.25)

hr()

```

Row {data-height=125}
-----------------------------------------
### Sales YTD
```{r}
totSalesVB <- 1000000000
totSalesVB <- formattable::currency(totSalesVB/1000000,digits=2)
renderValueBox ({
  valueBox(totSalesVB,
           caption = 'Sales YTD <br>(Millions)',
           color='#A12F28')
})
```
